version: "3.3"

services:
  web:
    image: webdevops/nginx:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.html
